name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has not touched in 60 days and will be marked as Stale. This issue will be closed if there is no activity within 7 days.'
          close-issue-message: 'This issue has been closed due to inactivity.'
          stale-pr-message: 'This PR has not been touched in 60 days and will be marked as Stale. This PR will be closed if there is no activity within 7 days.'
          close-pr-message: 'This PR has been closed due to inactivity.'
